### ISSUE TITLE
Configuration file is not created

### ISSUE THREAD

**Issue by Ved-un** [arch-anes/randwall#4]
Hello
I deleted the old configuration file in order to create a new one again, but for some reason it is not created.

The terminal writes:
```
~ >>> randwall                                                                 
Traceback (most recent call last):
  File "randwall", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "wallpaper.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "config.py", line 69, in <module>
  File "config.py", line 35, in __init__
  File "config.py", line 51, in _load_config
FileNotFoundError: [Errno 2] No such file or directory: '/home/ende/.config/randwall/config.json'
[61715] Failed to execute script randwall
~ >>>
```

**Comment by abelfodil** [comment]
Fixed! Thanks for reporting
